linting for python notebooks (experimental)

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -78,3 +78,20 @@ jobs:
         if: steps.check_tests.outputs.has_tests == 'true'
         run: python -m unittest
         shell: bash
+
+  py_notebook_linting:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: python version
+        run: python --version
+        shell: bash
+        if: always()
+      - name: install nbqa
+        run: |
+          python -  m pip install --upgrade pip
+          pip install nbqa
+        shell: bash
+      - name: Python Notebooks - Check Linting - nbqa
+        run: "nbqa pylint *.ipynb  || echo '::warning title=NoteBook QA Error(s)::Discuss solutions and trade-offs in code review.'"
+        shell: bash
